wc -l ../SparrowWorker/log/stats.txt
wc -l ../SparrowWorker_1/log/stats.txt
wc -l ../SparrowWorker_2/log/stats.txt
wc -l ../SparrowWorker_3/log/stats.txt
wc -l ../SparrowWorker_4/log/stats.txt
wc -l ../SparrowWorker_5/log/stats.txt
wc -l ../SparrowWorker_6/log/stats.txt
wc -l ../SparrowWorker_7/log/stats.txt
wc -l ../SparrowWorker_8/log/stats.txt
wc -l ../SparrowWorker_9/log/stats.txt
